export type BollywoodSongEntry = { title: string; movie: string; era: string }

export const BOLLYWOOD_SONGS: BollywoodSongEntry[] = [
  // Era 1: 1950s–80s
  { title: 'Mere Sapno Ki Rani', movie: 'Aradhana', era: '1950s-80s' },
  { title: 'Roop Tera Mastana', movie: 'Aradhana', era: '1950s-80s' },
  { title: 'Kora Kagaz Tha Ye Man Mera', movie: 'Aradhana', era: '1950s-80s' },
  { title: 'Chalte Chalte', movie: 'Pakeezah', era: '1950s-80s' },
  { title: 'Piya Tu Ab To Aaja', movie: 'Caravan', era: '1950s-80s' },
  { title: 'Dum Maro Dum', movie: 'Hare Rama Hare Krishna', era: '1950s-80s' },
  { title: 'Yeh Dosti', movie: 'Sholay', era: '1950s-80s' },
  { title: 'Mehbooba Mehbooba', movie: 'Sholay', era: '1950s-80s' },
  { title: 'Kabhi Kabhie Mere Dil Mein', movie: 'Kabhi Kabhie', era: '1950s-80s' },
  { title: 'Pal Pal Dil Ke Paas', movie: 'Blackmail', era: '1950s-80s' },
  { title: 'Lag Ja Gale', movie: 'Woh Kaun Thi', era: '1950s-80s' },
  { title: 'Mera Joota Hai Japani', movie: 'Shree 420', era: '1950s-80s' },
  { title: 'Pyar Hua Ikrar Hua', movie: 'Shree 420', era: '1950s-80s' },
  { title: 'Ae Dil Hai Mushkil', movie: 'CID', era: '1950s-80s' },
  { title: 'Jaane Kahan Gaye Woh Din', movie: 'Mera Naam Joker', era: '1950s-80s' },
  { title: 'Jeena Yahan Marna Yahan', movie: 'Mera Naam Joker', era: '1950s-80s' },
  { title: 'Ek Pyar Ka Nagma Hai', movie: 'Shor', era: '1950s-80s' },
  { title: 'Chura Liya Hai Tumne', movie: 'Yaadon Ki Baaraat', era: '1950s-80s' },
  { title: 'Yeh Shaam Mastani', movie: 'Kati Patang', era: '1950s-80s' },
  { title: 'Om Shanti Om', movie: 'Karz', era: '1950s-80s' },
  { title: 'Ek Ladki Bheegi Bhaagi Si', movie: 'Chalti Ka Naam Gaadi', era: '1950s-80s' },
  { title: 'Awara Hoon', movie: 'Awaara', era: '1950s-80s' },
  { title: 'Gaata Rahe Mera Dil', movie: 'Guide', era: '1950s-80s' },
  { title: 'Aaj Phir Jeene Ki Tamanna Hai', movie: 'Guide', era: '1950s-80s' },
  { title: 'Mere Samne Wali Khidki Mein', movie: 'Padosan', era: '1950s-80s' },
  { title: 'Ek Chatur Naar', movie: 'Padosan', era: '1950s-80s' },
  { title: 'Khaike Paan Banaras Wala', movie: 'Don', era: '1950s-80s' },
  { title: 'Yeh Mera Dil Yaar Ka Diwana', movie: 'Don', era: '1950s-80s' },
  { title: 'Hawa Hawai', movie: 'Mr. India', era: '1950s-80s' },
  { title: 'Kate Nahin Katte', movie: 'Mr. India', era: '1950s-80s' },
  { title: 'Dekha Ek Khwab', movie: 'Silsila', era: '1950s-80s' },
  { title: 'Rang Barse', movie: 'Silsila', era: '1950s-80s' },
  { title: 'Humein Tumse Pyar Kitna', movie: 'Kudrat', era: '1950s-80s' },
  { title: 'Tum Aa Gaye Ho Noor Aa Gaya', movie: 'Aandhi', era: '1950s-80s' },
  { title: 'Chhookar Mere Man Ko', movie: 'Yaarana', era: '1950s-80s' },
  { title: 'Tere Jaisa Yaar Kahan', movie: 'Yaarana', era: '1950s-80s' },
  { title: 'Ek Do Teen', movie: 'Tezaab', era: '1950s-80s' },
  { title: 'Papa Kehte Hain', movie: 'Qayamat Se Qayamat Tak', era: '1950s-80s' },
  { title: 'Aap Jaisa Koi', movie: 'Qurbani', era: '1950s-80s' },
  { title: 'I Am a Disco Dancer', movie: 'Disco Dancer', era: '1950s-80s' },
  { title: 'Jimmy Jimmy Aaja', movie: 'Disco Dancer', era: '1950s-80s' },
  { title: 'Mere Mehboob Qayamat Hogi', movie: 'Mr. X in Bombay', era: '1950s-80s' },
  { title: 'Pukarta Chala Hoon Main', movie: 'Mere Sanam', era: '1950s-80s' },
  { title: 'Tum Bin Jaaoon Kahan', movie: 'Pyar Ka Mausam', era: '1950s-80s' },
  { title: 'Zindagi Ka Safar', movie: 'Safar', era: '1950s-80s' },
  { title: 'Dafliwale Dafli Bajaa', movie: 'Sargam', era: '1950s-80s' },
  { title: 'Tu Tu Hai Wahi', movie: 'Yeh Vaada Raha', era: '1950s-80s' },
  { title: 'Ye Raatein Ye Mausam', movie: 'Dilli Ka Thug', era: '1950s-80s' },
  { title: 'Dil Deewana', movie: 'Maine Pyar Kiya', era: '1950s-80s' },
  { title: 'Jab Hum Jawan Honge', movie: 'Betaab', era: '1950s-80s' },

  // Era 2: 1990s
  { title: 'Tujhe Dekha To Ye Jaana Sanam', movie: 'DDLJ', era: '1990s' },
  { title: 'Mehndi Laga Ke Rakhna', movie: 'DDLJ', era: '1990s' },
  { title: 'Ghar Aaja Pardesi', movie: 'DDLJ', era: '1990s' },
  { title: 'Zara Sa Jhoom Loon Main', movie: 'DDLJ', era: '1990s' },
  { title: 'Ruk Ja O Dil Deewane', movie: 'DDLJ', era: '1990s' },
  { title: 'Tamma Tamma Loge', movie: 'Thanedaar', era: '1990s' },
  { title: 'Pehla Nasha', movie: 'Jo Jeeta Wohi Sikandar', era: '1990s' },
  { title: 'Chunari Chunari', movie: 'Biwi No. 1', era: '1990s' },
  { title: 'Jumma Chumma De De', movie: 'Hum', era: '1990s' },
  { title: 'Choli Ke Peeche', movie: 'Khal Nayak', era: '1990s' },
  { title: 'Dil To Pagal Hai', movie: 'Dil To Pagal Hai', era: '1990s' },
  { title: 'Koi Ladki Hai', movie: 'Dil To Pagal Hai', era: '1990s' },
  { title: 'Kuch Kuch Hota Hai', movie: 'Kuch Kuch Hota Hai', era: '1990s' },
  { title: 'Tujhe Yaad Na Meri Aayi', movie: 'Kuch Kuch Hota Hai', era: '1990s' },
  { title: 'Ladki Badi Anjani Hai', movie: 'Kuch Kuch Hota Hai', era: '1990s' },
  { title: 'Dhak Dhak Karne Laga', movie: 'Beta', era: '1990s' },
  { title: 'Ek Ladki Ko Dekha', movie: '1942: A Love Story', era: '1990s' },
  { title: 'Kuch Na Kaho', movie: '1942: A Love Story', era: '1990s' },
  { title: 'Tu Cheez Badi Hai Mast Mast', movie: 'Mohra', era: '1990s' },
  { title: 'Tip Tip Barsa Pani', movie: 'Mohra', era: '1990s' },
  { title: 'Chaiyya Chaiyya', movie: 'Dil Se', era: '1990s' },
  { title: 'Jiya Jale', movie: 'Dil Se', era: '1990s' },
  { title: 'Humma Humma', movie: 'Bombay', era: '1990s' },
  { title: 'Kehna Hi Kya', movie: 'Bombay', era: '1990s' },
  { title: 'Pardesi Pardesi Jana Nahi', movie: 'Raja Hindustani', era: '1990s' },
  { title: 'Aaye Ho Meri Zindagi Mein', movie: 'Raja Hindustani', era: '1990s' },
  { title: 'Raja Ko Rani Se', movie: 'Akele Hum Akele Tum', era: '1990s' },
  { title: 'Aati Kya Khandala', movie: 'Ghulam', era: '1990s' },
  { title: 'Ole Ole', movie: 'Yeh Dillagi', era: '1990s' },
  { title: 'Main Khiladi Tu Anari', movie: 'Main Khiladi Tu Anari', era: '1990s' },
  { title: 'Gup Chup Gup Chup', movie: 'Karan Arjun', era: '1990s' },
  { title: 'Yeh Bandhan To', movie: 'Karan Arjun', era: '1990s' },
  { title: 'Jeeta Tha Jiske Liye', movie: 'Dilwale', era: '1990s' },
  { title: 'O Baazigar', movie: 'Baazigar', era: '1990s' },
  { title: 'Yeh Kaali Kaali Aankhen', movie: 'Baazigar', era: '1990s' },
  { title: 'Mera Piya Ghar Aaya', movie: 'Yaarana', era: '1990s' },
  { title: 'Dilbar Dilbar', movie: 'Sirf Tum', era: '1990s' },
  { title: 'Do Dil Mil Rahe Hain', movie: 'Pardes', era: '1990s' },
  { title: 'I Love My India', movie: 'Pardes', era: '1990s' },
  { title: 'Chaand Chhupa Badal Mein', movie: 'Hum Dil De Chuke Sanam', era: '1990s' },
  { title: 'Dholi Taro Dhol Baaje', movie: 'Hum Dil De Chuke Sanam', era: '1990s' },
  { title: 'Chaand Taare', movie: 'Yes Boss', era: '1990s' },
  { title: 'Didi Tera Devar Deewana', movie: 'Hum Aapke Hain Koun', era: '1990s' },
  { title: 'Pehla Pehla Pyaar Hai', movie: 'Hum Aapke Hain Koun', era: '1990s' },
  { title: 'Taal Se Taal Mila', movie: 'Taal', era: '1990s' },
  { title: 'Jaadu Teri Nazar', movie: 'Darr', era: '1990s' },
  { title: 'Rangeela Re', movie: 'Rangeela', era: '1990s' },
  { title: 'Tanha Tanha', movie: 'Rangeela', era: '1990s' },
  { title: 'Sapne Mein Milti Hai', movie: 'Satya', era: '1990s' },
  { title: 'Mera Dil Bhi Kitna Pagal Hai', movie: 'Saajan', era: '1990s' },

  // Era 3: 2000–2009
  { title: 'Kaho Naa Pyaar Hai', movie: 'Kaho Naa Pyaar Hai', era: '2000s' },
  { title: 'Ek Pal Ka Jeena', movie: 'Kaho Naa Pyaar Hai', era: '2000s' },
  { title: 'Dil Chahta Hai', movie: 'Dil Chahta Hai', era: '2000s' },
  { title: 'Woh Ladki Hai Kahan', movie: 'Dil Chahta Hai', era: '2000s' },
  { title: 'Koi Kahe Kehta Rahe', movie: 'Dil Chahta Hai', era: '2000s' },
  { title: 'Radha Kaise Na Jale', movie: 'Lagaan', era: '2000s' },
  { title: 'O Rey Chhori', movie: 'Lagaan', era: '2000s' },
  { title: 'Bole Chudiyan', movie: 'Kabhi Khushi Kabhie Gham', era: '2000s' },
  { title: 'Suraj Hua Maddham', movie: 'Kabhi Khushi Kabhie Gham', era: '2000s' },
  { title: 'Say Shava Shava', movie: 'Kabhi Khushi Kabhie Gham', era: '2000s' },
  { title: 'Dola Re Dola', movie: 'Devdas', era: '2000s' },
  { title: 'Silsila Ye Chaahat Ka', movie: 'Devdas', era: '2000s' },
  { title: 'Mar Daala', movie: 'Devdas', era: '2000s' },
  { title: 'Jaadu Hai Nasha Hai', movie: 'Jism', era: '2000s' },
  { title: 'Kal Ho Naa Ho', movie: 'Kal Ho Naa Ho', era: '2000s' },
  { title: 'Maahi Ve', movie: 'Kal Ho Naa Ho', era: '2000s' },
  { title: "It's the Time to Disco", movie: 'Kal Ho Naa Ho', era: '2000s' },
  { title: 'Dhoom Machale', movie: 'Dhoom', era: '2000s' },
  { title: 'Tere Liye', movie: 'Veer-Zaara', era: '2000s' },
  { title: 'Tumse Milke Dil Ka Jo Haal', movie: 'Main Hoon Na', era: '2000s' },
  { title: 'Aashiq Banaya Aapne', movie: 'Aashiq Banaya Aapne', era: '2000s' },
  { title: 'Kajra Re', movie: 'Bunty Aur Babli', era: '2000s' },
  { title: 'Chaand Sifarish', movie: 'Fanaa', era: '2000s' },
  { title: 'Kabhi Alvida Naa Kehna', movie: 'Kabhi Alvida Naa Kehna', era: '2000s' },
  { title: 'Rock N Roll Soniye', movie: 'Kabhi Alvida Naa Kehna', era: '2000s' },
  { title: 'Mitwa', movie: 'Kabhi Alvida Naa Kehna', era: '2000s' },
  { title: 'Dhoom Again', movie: 'Dhoom 2', era: '2000s' },
  { title: 'Crazy Kiya Re', movie: 'Dhoom 2', era: '2000s' },
  { title: 'Beedi', movie: 'Omkara', era: '2000s' },
  { title: 'Namak Ishq Ka', movie: 'Omkara', era: '2000s' },
  { title: 'Bol Na Halke Halke', movie: 'Jhoom Barabar Jhoom', era: '2000s' },
  { title: 'Jhoom Barabar Jhoom', movie: 'Jhoom Barabar Jhoom', era: '2000s' },
  { title: 'Rang De Basanti', movie: 'Rang De Basanti', era: '2000s' },
  { title: 'Tum Se Hi', movie: 'Jab We Met', era: '2000s' },
  { title: 'Yeh Ishq Haaye', movie: 'Jab We Met', era: '2000s' },
  { title: 'Aaoge Jab Tum', movie: 'Jab We Met', era: '2000s' },
  { title: 'Dard-e-Disco', movie: 'Om Shanti Om', era: '2000s' },
  { title: 'Deewangi Deewangi', movie: 'Om Shanti Om', era: '2000s' },
  { title: 'Ajab Si', movie: 'Om Shanti Om', era: '2000s' },
  { title: 'Chak De India', movie: 'Chak De India', era: '2000s' },
  { title: 'Pehli Nazar Mein', movie: 'Race', era: '2000s' },
  { title: 'Desi Girl', movie: 'Dostana', era: '2000s' },
  { title: 'Jai Ho', movie: 'Slumdog Millionaire', era: '2000s' },
  { title: 'Tujh Mein Rab Dikhta Hai', movie: 'Rab Ne Bana Di Jodi', era: '2000s' },
  { title: 'Haule Haule', movie: 'Rab Ne Bana Di Jodi', era: '2000s' },
  { title: "Pappu Can't Dance Saala", movie: 'Jaane Tu… Ya Jaane Na', era: '2000s' },
  { title: 'Masakali', movie: 'Delhi-6', era: '2000s' },
  { title: 'Genda Phool', movie: 'Delhi-6', era: '2000s' },
  { title: 'All Izz Well', movie: '3 Idiots', era: '2000s' },
  { title: 'Zoobi Doobi', movie: '3 Idiots', era: '2000s' },

  // Era 4: 2010–now
  { title: 'Munni Badnaam Hui', movie: 'Dabangg', era: '2010s' },
  { title: 'Tere Mast Mast Do Nain', movie: 'Dabangg', era: '2010s' },
  { title: 'Sheila Ki Jawani', movie: 'Tees Maar Khan', era: '2010s' },
  { title: 'Kun Faya Kun', movie: 'Rockstar', era: '2010s' },
  { title: 'Sadda Haq', movie: 'Rockstar', era: '2010s' },
  { title: 'Chammak Challo', movie: 'Ra.One', era: '2010s' },
  { title: 'Tum Hi Ho', movie: 'Aashiqui 2', era: '2010s' },
  { title: 'Chahun Main Ya Naa', movie: 'Aashiqui 2', era: '2010s' },
  { title: 'Sunn Raha Hai Na Tu', movie: 'Aashiqui 2', era: '2010s' },
  { title: 'Balam Pichkari', movie: 'Yeh Jawaani Hai Deewani', era: '2010s' },
  { title: 'Badtameez Dil', movie: 'Yeh Jawaani Hai Deewani', era: '2010s' },
  { title: 'Kabira', movie: 'Yeh Jawaani Hai Deewani', era: '2010s' },
  { title: 'Subhanallah', movie: 'Yeh Jawaani Hai Deewani', era: '2010s' },
  { title: 'Lungi Dance', movie: 'Chennai Express', era: '2010s' },
  { title: 'Gerua', movie: 'Dilwale', era: '2010s' },
  { title: 'Malhari', movie: 'Bajirao Mastani', era: '2010s' },
  { title: 'Deewani Mastani', movie: 'Bajirao Mastani', era: '2010s' },
  { title: 'Pinga', movie: 'Bajirao Mastani', era: '2010s' },
  { title: 'Sooraj Dooba Hai', movie: 'Roy', era: '2010s' },
  { title: 'Gallan Goodiyan', movie: 'Dil Dhadakne Do', era: '2010s' },
  { title: 'Kala Chashma', movie: 'Baar Baar Dekho', era: '2010s' },
  { title: 'Kar Gayi Chull', movie: 'Kapoor & Sons', era: '2010s' },
  { title: 'Ae Dil Hai Mushkil', movie: 'Ae Dil Hai Mushkil', era: '2010s' },
  { title: 'Channa Mereya', movie: 'Ae Dil Hai Mushkil', era: '2010s' },
  { title: 'Bulleya', movie: 'Ae Dil Hai Mushkil', era: '2010s' },
  { title: 'Hawayein', movie: 'Jab Harry Met Sejal', era: '2010s' },
  { title: 'Tamma Tamma Again', movie: 'Badrinath Ki Dulhania', era: '2010s' },
  { title: 'Dilbar', movie: 'Satyameva Jayate', era: '2010s' },
  { title: 'Aankh Marey', movie: 'Simmba', era: '2010s' },
  { title: 'Ghoomar', movie: 'Padmaavat', era: '2010s' },
  { title: 'Apna Time Aayega', movie: 'Gully Boy', era: '2010s' },
  { title: 'Ghungroo', movie: 'War', era: '2010s' },
  { title: 'Bekhayali', movie: 'Kabir Singh', era: '2010s' },
  { title: 'Tujhe Kitna Chahne Lage', movie: 'Kabir Singh', era: '2010s' },
  { title: 'Raataan Lambiyan', movie: 'Shershaah', era: '2010s' },
  { title: 'Ranjha', movie: 'Shershaah', era: '2010s' },
  { title: 'Param Sundari', movie: 'Mimi', era: '2010s' },
  { title: 'Kesariya', movie: 'Brahmastra', era: '2010s' },
  { title: 'Deva Deva', movie: 'Brahmastra', era: '2010s' },
  { title: 'Besharam Rang', movie: 'Pathaan', era: '2010s' },
  { title: 'Jhoome Jo Pathaan', movie: 'Pathaan', era: '2010s' },
  { title: 'Zinda Banda', movie: 'Jawan', era: '2010s' },
  { title: 'Chaleya', movie: 'Jawan', era: '2010s' },
  { title: 'Apna Bana Le', movie: 'Bhediya', era: '2010s' },
  { title: 'What Jhumka?', movie: 'Rocky Aur Rani Kii Prem Kahaani', era: '2010s' },
  { title: 'Tum Kya Mile', movie: 'Rocky Aur Rani Kii Prem Kahaani', era: '2010s' },
  { title: 'Tere Vaaste', movie: 'Zara Hatke Zara Bachke', era: '2010s' },
  { title: 'O Bedardeya', movie: 'Tu Jhoothi Main Makkaar', era: '2010s' },
  { title: 'Saiyaara', movie: 'Saiyaara', era: '2010s' },
  { title: 'Jag Ghoomeya', movie: 'Sultan', era: '2010s' },
]
