export const FIVE_SECOND_RULE_GENERAL_CARDS = [
  "Name 3 things that are silent",
  "Name 3 things you'd find in a hotel minibar",
  "Name 3 things you'd find in a restaurant",
  "Name 3 things you'd do when you're bored",
  "Name 3 DC characters",
  "Name 3 things that are colorful",
  "Name 3 things that are illegal in some places",
  "Name 3 things at a music festival",
  "Name 3 things you'd find in a hotel room",
  "Name 3 things that are rare",
  "Name 3 apps that help you stay fit",
  "Name 3 action-packed TV shows",
  "Name 3 types of burgers",
  "Name 3 things you'd eat cold",
  "Name 3 types of dressing",
  "Name 3 types of salad",
  "Name 3 things at a barbecue",
  "Name 3 things you'd drink when you're sick",
  "Name 3 apps that help you sleep better",
  "Name 3 types of bears",
  "Name 3 types of planes",
  "Name 3 types of pasta sauce",
  "Name 3 types of wine",
  "Name 3 things that are furry",
  "Name 3 brands of laptops",
  "Name 3 famous Williams",
  "Name 3 types of energy drinks",
  "Name 3 types of vehicles",
  "Name 3 things you'd find in a stadium",
  "Name 3 U.S. states that start with the letter O",
  "Name 3 types of pancakes",
  "Name 3 things you'd find in a teenager's room",
  "Name 3 things that are salty",
  "Name 3 things you'd pack for a backpacking trip",
  "Name 3 things you'd find in a construction site",
  "Name 3 underrated TV shows",
  "Name 3 types of pizza",
  "Name 3 things that are banned from airplanes",
  "Name 3 things you'd find in a temple",
  "Name 3 types of rocks",
  "Name 3 things at a sporting event",
  "Name 3 things that are gold",
  "Name 3 types of spices",
  "Name 3 things that are electric",
  "Name 3 types of locks",
  "Name 3 things that melt",
  "Name 3 animated songs",
  "Name 3 funny songs",
  "Name 3 jobs that require being brave",
  "Name 3 things you'd find in a aquarium",
  "Name 3 things that are common",
  "Name 3 things that squeak",
  "Name 3 types of nails",
  "Name 3 funny books",
  "Name 3 underrated songs",
  "Name 3 things that are light",
  "Name 3 types of flowers",
  "Name 3 types of masks",
  "Name 3 movies with sequels",
  "Name 3 things you'd wear to a wedding",
  "Name 3 apps that help you find a date",
  "Name 3 things you'd learn from YouTube",
  "Name 3 things you'd find in a pirate ship",
  "Name 3 Pixar movies",
  "Name 3 things that are invisible",
  "Name 3 things you'd find in space",
  "Name 3 U.S. states that start with the letter C",
  "Name 3 animated movies",
  "Name 3 things you'd do before an exam",
  "Name 3 things you'd find in a farm",
  "Name 3 types of martial arts",
  "Name 3 brands of hotels",
  "Name 3 things that are waterproof",
  "Name 3 things you'd keep in the bathroom",
  "Name 3 things that are cheap",
  "Name 3 Bollywood actors",
  "Name 3 things at a picnic",
  "Name 3 things that are high-tech",
  "Name 3 things that are square",
  "Name 3 things you do before bed",
  "Name 3 cartoon characters",
  "Name 3 classic movies",
  "Name 3 things you'd whisper",
  "Name 3 pizza toppings",
  "Name 3 brands of chips",
  "Name 3 things you'd eat for dessert",
  "Name 3 things that are blue",
  "Name 3 things that are biodegradable",
  "Name 3 mysterious movies",
  "Name 3 brands of toothpaste",
  "Name 3 famous Michaels",
  "Name 3 types of phones",
  "Name 3 jobs that require good eyesight",
  "Name 3 brands of clothing brands",
  "Name 3 things that are tiny",
  "Name 3 things that are quiet",
  "Name 3 types of hats",
  "Name 3 things you'd find in a airport",
  "Name 3 things at a graduation",
  "Name 3 things you'd call a professional for",
  "Name 3 sports played with a racket",
  "Name 3 romantic songs",
  "Name 3 things you'd find in a office",
  "Name 3 types of noodles",
  "Name 3 types of clouds",
  "Name 3 things you'd find in a grocery store",
  "Name 3 things that are hard to pronounce",
  "Name 3 types of glue",
  "Name 3 apps that help you manage money",
  "Name 3 types of screwdrivers",
  "Name 3 types of camping stoves",
  "Name 3 things people are allergic to",
  "Name 3 things you'd practice to get better at",
  "Name 3 things you'd find in a hospital",
  "Name 3 things you'd find in a gas station",
  "Name 3 things in a first aid kit",
  "Name 3 apps that help you take notes",
  "Name 3 brands of coffee chains",
  "Name 3 things you'd find in a desert",
  "Name 3 famous Priyas",
  "Name 3 romantic TV shows",
  "Name 3 mysterious TV shows",
  "Name 3 types of backpacks",
  "Name 3 things at a baby shower",
  "Name 3 types of waffles",
  "Name 3 countries that start with the letter C",
  "Name 3 things you'd keep on your desk",
  "Name 3 musical TV shows",
  "Name 3 U.S. states that start with the letter K",
  "Name 3 mysterious songs",
  "Name 3 things you'd find in a zoo",
  "Name 3 breakfast foods",
  "Name 3 things you'd do at a sleepover",
  "Name 3 things that float",
  "Name 3 things you'd find in a arena",
  "Name 3 things at a road trip",
  "Name 3 animated books",
  "Name 3 types of jewelry",
  "Name 3 things you'd do in the rain",
  "Name 3 types of card games",
  "Name 3 brands of ice cream",
  "Name 3 things you'd find in a forest",
  "Name 3 things that are gigantic",
  "Name 3 types of cameras",
  "Name 3 musical books",
  "Name 3 famous Annas",
  "Name 3 things you'd find in a playground",
  "Name 3 types of puzzles",
  "Name 3 countries in Europe",
  "Name 3 things you'd keep secret",
  "Name 3 months of the year",
  "Name 3 apps that help you shop online",
  "Name 3 things you'd write in a diary",
  "Name 3 types of muffins",
  "Name 3 superheroes",
  "Name 3 things that are smelly",
  "Name 3 reptiles",
  "Name 3 things that are sour",
  "Name 3 things you'd bring on a road trip",
  "Name 3 things you'd find in a train station",
  "Name 3 types of chairs",
  "Name 3 types of toothpaste",
  "Name 3 brands of coffee",
  "Name 3 things that glow in the dark",
  "Name 3 things that are spiky",
  "Name 3 things you'd do on a first date",
  "Name 3 things that are round",
  "Name 3 things that are shiny",
  "Name 3 jobs that require working with kids",
  "Name 3 types of trucks",
  "Name 3 jobs that require a license",
  "Name 3 things that are sharp",
  "Name 3 things you'd find in a garage",
  "Name 3 things in a school bag",
  "Name 3 things pirates search for",
  "Name 3 sports played with a board",
  "Name 3 U.S. states that start with the letter A",
  "Name 3 things at a school reunion",
  "Name 3 things that are hard to spell",
  "Name 3 things you'd recycle",
  "Name 3 things you'd find in a recording studio",
  "Name 3 U.S. states that start with the letter T",
  "Name 3 sounds animals make",
  "Name 3 apps that help you stay in touch",
  "Name 3 brands of video game consoles",
  "Name 3 brands of washing machines",
  "Name 3 things you'd find in a spaceship",
  "Name 3 famous Rajs",
  "Name 3 types of seeds",
  "Name 3 things at a New Year's Eve party",
  "Name 3 board games",
  "Name 3 types of tools",
  "Name 3 things banks keep in a vault",
  "Name 3 sports played with skates",
  "Name 3 things under the bed",
  "Name 3 scary songs",
  "Name 3 things you'd find in a cafe",
  "Name 3 animals that live in a farm",
  "Name 3 brands of refrigerators",
  "Name 3 things that are futuristic",
  "Name 3 sports played with a paddle",
  "Name 3 things that are mass-produced",
  "Name 3 things you can fold",
  "Name 3 Looney Tunes characters",
  "Name 3 things that are dangerous",
  "Name 3 things you'd see at a circus",
  "Name 3 things that are purple",
  "Name 3 types of birds",
  "Name 3 brands of shampoo",
  "Name 3 musical movies",
  "Name 3 Pixar characters",
  "Name 3 types of wallets",
  "Name 3 things at a birthday party",
  "Name 3 things you'd find at the bottom of the ocean",
  "Name 3 things a magician uses",
  "Name 3 things astronauts do in space",
  "Name 3 jobs that require a uniform",
  "Name 3 types of fabric",
  "Name 3 countries in Africa",
  "Name 3 things that are disposable",
  "Name 3 things that are slimy",
  "Name 3 brands of power tools",
  "Name 3 types of clothing",
  "Name 3 types of board games",
  "Name 3 types of pastries",
  "Name 3 classic TV shows",
  "Name 3 animals that live in the jungle",
  "Name 3 things you'd bring to a picnic",
  "Name 3 things you'd find in a toolbox",
  "Name 3 The Simpsons characters",
  "Name 3 jobs that require traveling a lot",
  "Name 3 things at a wedding",
  "Name 3 famous Roberts",
  "Name 3 Disney characters",
  "Name 3 jobs that require working at night",
  "Name 3 things you'd find in a living room",
  "Name 3 brands of credit cards",
  "Name 3 jobs that require working outdoors",
  "Name 3 types of smoothies",
  "Name 3 things that are man-made",
  "Name 3 things you'd keep as a souvenir",
  "Name 3 things you'd find in a library",
  "Name 3 types of soda",
  "Name 3 types of candy",
  "Name 3 things you'd wear to the gym",
  "Name 3 famous Anas",
  "Name 3 types of lamps",
  "Name 3 things that are cold",
  "Name 3 things you'd keep in your wallet",
  "Name 3 things you'd see in a superhero movie",
  "Name 3 things you'd find in a toy store",
  "Name 3 types of sauce",
  "Name 3 things that make you sneeze",
  "Name 3 types of dance",
  "Name 3 things at a camping trip",
  "Name 3 things kids are scared of",
  "Name 3 types of shampoo",
  "Name 3 things you'd find in a salon",
  "Name 3 things that are slippery",
  "Name 3 things you'd learn in school",
  "Name 3 things you can paint",
  "Name 3 Marvel movies",
  "Name 3 things in the sky",
  "Name 3 fruits",
  "Name 3 types of onions",
  "Name 3 things you'd pack for a honeymoon trip",
  "Name 3 jobs that require strength",
  "Name 3 types of milk",
  "Name 3 things you plug into a wall",
  "Name 3 types of yoga mats",
  "Name 3 U.S. states that start with the letter I",
  "Name 3 things you'd fix yourself",
  "Name 3 classic songs",
  "Name 3 musical songs",
  "Name 3 things you'd find in grandma's house",
  "Name 3 countries in Oceania",
  "Name 3 famous Sophias",
  "Name 3 types of cheese",
  "Name 3 things you'd find in a amusement park",
  "Name 3 things that are soft",
  "Name 3 things that are old-fashioned",
  "Name 3 famous Alexes",
  "Name 3 jobs that require working with animals",
  "Name 3 types of peppers",
  "Name 3 things you'd find in a church",
  "Name 3 Star Trek characters",
  "Name 3 things you wear",
  "Name 3 things that are white",
  "Name 3 things you'd find in a mall",
  "Name 3 types of vitamins",
  "Name 3 famous Davids",
  "Name 3 animals that live in a coral reef",
  "Name 3 things you'd collect as a hobby",
  "Name 3 types of beer",
  "Name 3 things you'd find in a bathroom",
  "Name 3 things you'd build with your hands",
  "Name 3 things you'd find in a bedroom",
  "Name 3 types of crackers",
  "Name 3 things you'd throw away",
  "Name 3 things that are brown",
  "Name 3 types of party games",
  "Name 3 types of drums",
  "Name 3 famous Toms",
  "Name 3 brands of sneakers",
  "Name 3 things you'd find in a bus stop",
  "Name 3 Star Wars characters",
  "Name 3 countries in Asia",
  "Name 3 things you'd say to a baby",
  "Name 3 types of swimsuits",
  "Name 3 things that are reusable",
  "Name 3 animals that live in the Arctic",
  "Name 3 famous Lucys",
  "Name 3 brands of headphones",
  "Name 3 award-winning songs",
  "Name 3 things that are fragile",
  "Name 3 things you'd find in a purse",
  "Name 3 jobs that require a college degree",
  "Name 3 things that are seasonal",
  "Name 3 types of tables",
  "Name 3 funny TV shows",
  "Name 3 funny movies",
  "Name 3 types of sushi",
  "Name 3 types of perfume",
  "Name 3 things you'd find in a bank",
  "Name 3 types of guitars",
  "Name 3 types of nuts",
  "Name 3 things you'd see on a farm",
  "Name 3 brands of luggage",
  "Name 3 mysterious books",
  "Name 3 types of backpacking gear",
  "Name 3 things that are hot",
  "Name 3 things that are sweet",
  "Name 3 types of bikes",
  "Name 3 famous Jameses",
  "Name 3 things you'd forget at home",
  "Name 3 things that fly",
  "Name 3 types of chocolate",
  "Name 3 things you'd pack for a road trip",
  "Name 3 things you'd find in a fire station",
  "Name 3 types of fishing gear",
  "Name 3 brands of soda",
  "Name 3 sports played with a net",
  "Name 3 things you'd find in a submarine",
  "Name 3 classic books",
  "Name 3 yellow foods",
  "Name 3 things that are orange",
  "Name 3 things you'd plug in",
  "Name 3 types of jackets",
  "Name 3 types of donuts",
  "Name 3 things you'd pack for a beach trip",
  "Name 3 things you'd find in a circus",
  "Name 3 of the Great Lakes",
  "Name 3 types of medicine",
  "Name 3 types of keys",
  "Name 3 sad books",
  "Name 3 things in a fridge",
  "Name 3 award-winning books",
  "Name 3 brands of sunglasses",
  "Name 3 Disney movies",
  "Name 3 things that are ancient",
  "Name 3 famous Lilys",
  "Name 3 things that are handmade",
  "Name 3 things that are black",
  "Name 3 countries in North America",
  "Name 3 types of video games",
  "Name 3 jobs that require math",
  "Name 3 types of bread",
  "Name 3 types of cereal",
  "Name 3 types of cocktails",
  "Name 3 types of watches",
  "Name 3 things you'd pack for a ski trip",
  "Name 3 types of soap",
  "Name 3 things you'd give as a gift",
  "Name 3 things you'd do to relax",
  "Name 3 things you'd learn as a kid",
  "Name 3 types of trees",
  "Name 3 things you'd find in a parking lot",
  "Name 3 scary movies",
  "Name 3 things you'd find in a police station",
  "Name 3 things that are flexible",
  "Name 3 types of pajamas",
  "Name 3 types of beans",
  "Name 3 things you'd yell at a sports game",
  "Name 3 types of coffee",
  "Name 3 things you'd find at a ski resort",
  "Name 3 types of rice",
  "Name 3 brands of fast food chains",
  "Name 3 U.S. states that start with the letter V",
  "Name 3 underrated movies",
  "Name 3 countries in South America",
  "Name 3 things you'd find in a art studio",
  "Name 3 things you'd find in a museum",
  "Name 3 famous Johns",
  "Name 3 ice cream flavors",
  "Name 3 things you'd break by accident",
  "Name 3 types of cake",
  "Name 3 award-winning TV shows",
  "Name 3 jobs that require being organized",
  "Name 3 sports played with a bat",
  "Name 3 things you'd do to stay healthy",
  "Name 3 things people collect",
  "Name 3 things you'd bring camping",
  "Name 3 things that are found in nature",
  "Name 3 types of exercise equipment",
  "Name 3 types of oil",
  "Name 3 things you'd find in a gym",
  "Name 3 famous Marias",
  "Name 3 based-on-a-true-story songs",
  "Name 3 things adults are scared of",
  "Name 3 things at a Halloween party",
  "Name 3 things that bounce",
  "Name 3 Marvel characters",
  "Name 3 things a chef needs in a kitchen",
  "Name 3 things that are loud",
  "Name 3 types of yoga poses",
  "Name 3 shows on Netflix",
  "Name 3 apps that help you get around",
  "Name 3 things you'd search for online",
  "Name 3 things you'd do on a road trip",
  "Name 3 things you'd pack for a winter trip",
  "Name 3 Lord of the Rings characters",
  "Name 3 things you'd bring to a job interview",
  "Name 3 things you'd pack for a cruise trip",
  "Name 3 things you'd find in a diaper bag",
  "Name 3 apps that help you order food",
  "Name 3 underrated books",
  "Name 3 things you'd find in a backyard",
  "Name 3 types of sandwiches",
  "Name 3 things that are green",
  "Name 3 things you'd pack for a camping trip",
  "Name 3 things that sink",
  "Name 3 things that are crunchy",
  "Name 3 brands of cars",
  "Name 3 U.S. states that start with the letter W",
  "Name 3 types of video game consoles",
  "Name 3 U.S. states that start with the letter M",
  "Name 3 brands of airlines",
  "Name 3 romantic movies",
  "Name 3 types of gloves",
  "Name 3 things that are expensive",
  "Name 3 types of music",
  "Name 3 things you'd find in a castle",
  "Name 3 things you'd see at a farmers market",
  "Name 3 jobs that require good hearing",
  "Name 3 types of soup",
  "Name 3 types of herbs",
  "Name 3 things you'd bring to a desert island",
  "Name 3 things that are noisy",
  "Name 3 types of sports",
  "Name 3 scary books",
  "Name 3 types of hammers",
  "Name 3 types of eggs",
  "Name 3 types of paint",
  "Name 3 types of snakes",
  "Name 3 things you'd find in a bakery",
  "Name 3 things you'd find in a beach",
  "Name 3 things at a funeral",
  "Name 3 things that are spicy",
  "Name 3 things at a office party",
  "Name 3 things you'd keep in your car",
  "Name 3 types of light bulbs",
  "Name 3 things that come in pairs",
  "Name 3 action-packed books",
  "Name 3 apps that help you book a trip",
  "Name 3 things that are silver",
  "Name 3 things you'd regret eating too much of",
  "Name 3 types of potatoes",
  "Name 3 things you'd find in a basement",
  "Name 3 types of jeans",
  "Name 3 types of shoes",
  "Name 3 jobs that require a steady hand",
  "Name 3 things you'd find in a post office",
  "Name 3 jobs that require years of training",
  "Name 3 types of insects",
  "Name 3 sports played with a ball",
  "Name 3 types of necklaces",
  "Name 3 types of pie",
  "Name 3 things with wheels",
  "Name 3 based-on-a-true-story TV shows",
  "Name 3 based-on-a-true-story movies",
  "Name 3 vegetables",
  "Name 3 types of boats",
  "Name 3 animals that live in the savanna",
  "Name 3 things you'd find in a concert hall",
  "Name 3 types of weather",
  "Name 3 animals that live in a forest",
  "Name 3 things you'd lose easily",
  "Name 3 sad songs",
  "Name 3 famous Olivias",
  "Name 3 types of pasta",
  "Name 3 types of weights",
  "Name 3 things you'd regret buying",
  "Name 3 things you'd pack for a tropical trip",
  "Name 3 things that are yellow",
  "Name 3 brands of backpacks",
  "Name 3 animals that live in the ocean",
  "Name 3 things you'd say when you're excited",
  "Name 3 romantic books",
  "Name 3 types of fish",
  "Name 3 types of socks",
  "Name 3 animated TV shows",
  "Name 3 types of furniture",
  "Name 3 things that are heavy",
  "Name 3 types of grains",
  "Name 3 famous Chrises",
  "Name 3 famous Kevins",
  "Name 3 types of trains",
  "Name 3 things that pop",
  "Name 3 types of curry",
  "Name 3 things you'd eat with your hands",
  "Name 3 things you'd find in a classroom",
  "Name 3 things to do on the weekend",
  "Name 3 jobs that require creativity",
  "Name 3 brands of pizza chains",
  "Name 3 types of bags",
  "Name 3 famous Emmas",
  "Name 3 types of tea",
  "Name 3 types of batteries",
  "Name 3 things you'd find in a doctor's office",
  "Name 3 things that are bitter",
  "Name 3 jobs that require patience",
  "Name 3 things you'd find at a gas station",
  "Name 3 famous Henrys",
  "Name 3 things you'd pack for a hiking trip",
  "Name 3 things that are wireless",
  "Name 3 types of candles",
  "Name 3 brands of jeans",
  "Name 3 types of costumes",
  "Name 3 action-packed movies",
  "Name 3 types of bandages",
  "Name 3 sad movies",
  "Name 3 things that are transparent",
  "Name 3 apps that help you listen to music",
  "Name 3 scary TV shows",
  "Name 3 things you'd pack for a safari trip",
  "Name 3 types of tacos",
  "Name 3 things you'd say when you're annoyed",
  "Name 3 things you'd find in a barbershop",
  "Name 3 types of computers",
  "Name 3 brands of watches",
  "Name 3 types of rope",
  "Name 3 U.S. states that start with the letter N",
  "Name 3 brands of TVs",
  "Name 3 animals people keep as pets",
  "Name 3 apps that help you edit photos",
  "Name 3 award-winning movies",
  "Name 3 things you'd find in a attic",
  "Name 3 things that are pink",
  "Name 3 things that are red",
  "Name 3 types of cookies",
  "Name 3 types of currency",
  "Name 3 animals that live in the mountains",
  "Name 3 things that are magnetic",
  "Name 3 animals that live in a cave",
  "Name 3 movies about animals",
  "Name 3 animals that live in the desert",
  "Name 3 brands of chocolate",
  "Name 3 brands of cereal",
  "Name 3 famous Mias",
  "Name 3 things you put on toast",
  "Name 3 types of umbrellas",
  "Name 3 types of rings",
  "Name 3 types of chips",
  "Name 3 things you'd find in a movie theater",
  "Name 3 apps that help you learn a language",
  "Name 3 things you'd wear in the snow",
  "Name 3 types of makeup",
  "Name 3 types of cheese boards",
  "Name 3 famous Ellas",
  "Name 3 types of mushrooms",
  "Name 3 based-on-a-true-story books",
  "Name 3 things you'd find on a golf course",
  "Name 3 musical instruments",
  "Name 3 things that are sticky",
  "Name 3 things you'd find in a jungle",
  "Name 3 types of sleeping bags",
  "Name 3 jobs that require public speaking",
  "Name 3 things you'd find in a dentist's office",
  "Name 3 apps that help you watch movies",
  "Name 3 types of exercise",
  "Name 3 U.S. states",
  "Name 3 sad TV shows",
  "Name 3 sports played with a stick",
  "Name 3 types of monkeys",
  "Name 3 Harry Potter characters",
  "Name 3 types of clocks",
  "Name 3 dog breeds",
  "Name 3 famous Sarahs",
  "Name 3 U.S. Presidents",
  "Name 3 apps that help you split a bill",
  "Name 3 things you'd find in a pharmacy",
  "Name 3 things you'd find in a kitchen",
  "Name 3 famous Jacks",
  "Name 3 things you'd fold",
  "Name 3 things you'd find in a farmers market",
  "Name 3 types of juice",
  "Name 3 types of tents",
  "Name 3 things you'd post on social media",
  "Name 3 things you'd pack for a business trip",
  "Name 3 types of tape",
  "Name 3 things you'd find in a science lab",
  "Name 3 animals that live in a river",
  "Name 3 brands of phones",
  "Name 3 types of sunglasses",
  "Name 3 action-packed songs",
  "Name 3 types of spiders",
  "Name 3 things you'd recharge",
  "Name 3 animals that live in a rainforest",
  "Name 3 things you'd find in a courtroom",
  "Name 3 famous Noahs",
]
