// Wavelength spectra. Each round the Psychic secretly dials a hidden target somewhere
// between the two labels, then gives a clue that points to that spot on the dial.
export const WAVELENGTH_SPECTRA: [string, string][] = [
  ["Hot", "Cold"], ["Expensive", "Cheap"], ["Strong", "Weak"],
  ["Boring Hobby", "Interesting Hobby"], ["Sad Song", "Happy Song"],
  ["Overrated", "Underrated"], ["Famous", "Obscure"], ["Safe", "Dangerous"],
  ["Simple", "Complex"], ["Boring Job", "Exciting Job"], ["Bad Gift", "Good Gift"],
  ["Cheap Date", "Expensive Date"], ["Small Talk", "Deep Conversation"],
  ["Predictable Movie", "Unpredictable Movie"], ["Casual Outfit", "Formal Outfit"],
  ["Healthy Food", "Junk Food"], ["Quiet Place", "Loud Place"],
  ["Old Fashioned", "Modern"], ["Realistic", "Fantastical"],
  ["Practical Gift", "Sentimental Gift"], ["Introvert Activity", "Extrovert Activity"],
  ["Guilty Pleasure", "Respectable Hobby"], ["Low Effort", "High Effort"],
  ["Slow", "Fast"], ["Cheap Wine", "Expensive Wine"],
  ["Bad First Date", "Great First Date"], ["Relaxing Vacation", "Adventurous Vacation"],
  ["Comfort Food", "Fancy Food"], ["Underdog", "Favorite"], ["Villain", "Hero"],
  ["Tragic Ending", "Happy Ending"], ["Serious Movie", "Comedy Movie"],
  ["Casual Friendship", "Best Friend"], ["Budget Trip", "Luxury Trip"],
  ["Quiet Neighborhood", "Busy City"], ["Simple Recipe", "Gourmet Recipe"],
  ["Rookie", "Veteran"], ["Amateur", "Professional"], ["Cheap Toy", "Expensive Toy"],
  ["Underrated Movie", "Overrated Movie"], ["Scary Movie", "Funny Movie"],
  ["Sad Movie", "Uplifting Movie"], ["Predictable Plot Twist", "Shocking Plot Twist"],
  ["Small Wedding", "Big Wedding"], ["Casual Hangout", "Big Party"],
  ["Low-Key Celebrity", "A-List Celebrity"], ["Minor Inconvenience", "Major Disaster"],
  ["Mild Spice", "Extremely Spicy"], ["Short Book", "Long Book"],
  ["Easy Workout", "Intense Workout"], ["Chill Music", "Hype Music"],
  ["Cheap Souvenir", "Meaningful Souvenir"], ["Fast Food", "Fine Dining"],
  ["Small Dog", "Big Dog"], ["Weekday", "Weekend"], ["Rainy Day", "Sunny Day"],
  ["Winter", "Summer"], ["Sunrise", "Sunset"], ["Whisper", "Shout"],
  ["Village", "Metropolis"], ["Handwritten Letter", "Text Message"],
  ["Old Movie", "New Movie"], ["Classic Rock", "Pop Music"],
  ["Tea Person", "Coffee Person"], ["Cat Person", "Dog Person"],
  ["Early Bird", "Night Owl"], ["Homebody", "Social Butterfly"],
  ["Minimalist", "Maximalist"], ["Cautious", "Reckless"],
  ["Frugal", "Extravagant"], ["Humble", "Boastful"], ["Optimist", "Pessimist"],
  ["Planner", "Improviser"], ["Introvert", "Extrovert"], ["Traditional", "Trendy"],
  ["Local", "Touristy"], ["Nostalgic", "Futuristic"], ["Cozy", "Glamorous"],
  ["Subtle", "Over-the-top"], ["Gentle", "Intense"], ["Calm", "Chaotic"],
  ["Familiar", "Exotic"], ["Common", "Rare"], ["Cheap Thrill", "Bucket List Experience"],
  ["Guilty Snack", "Healthy Snack"], ["Small Gesture", "Grand Gesture"],
  ["Quick Trip", "Long Journey"], ["Basic", "Fancy"], ["Ordinary", "Extraordinary"],
  ["Indoor Hobby", "Outdoor Hobby"], ["Team Sport", "Solo Sport"],
  ["Beach Vacation", "Mountain Vacation"], ["Morning Person", "Night Person"],
  ["Book", "Movie"], ["City Life", "Country Life"], ["Spontaneous", "Scheduled"],
  ["Quiet Date Night", "Big Night Out"], ["Sweet", "Savory"],
  ["Cheap Flight", "Business Class"], ["Practical Car", "Dream Car"],
  ["Small Talk Topic", "Controversial Topic"], ["Bad Joke", "Great Joke"],
  ["Underdog Story", "Rags-to-Riches Story"], ["Mild Winter", "Brutal Winter"],
  ["Light Read", "Heavy Read"], ["Casual Fan", "Superfan"],
  ["Low-Stakes Game", "High-Stakes Game"], ["Cheap Thrill Ride", "Extreme Roller Coaster"],
  ["Understated", "Flashy"], ["Cautious Investment", "Risky Investment"],
  ["Everyday Outfit", "Red Carpet Outfit"], ["Small Apartment", "Mansion"],
  ["Short Commute", "Long Commute"], ["Mild Celebrity Gossip", "Huge Scandal"],
]
