export interface KidsGame {
  slug: string
  name: string
  emoji: string
  description: string
  rules: string[]
  examples: { question: string; answer: string }[]
  prompts: string[]
  reminder: string
  mistakeLabel: string
}

export const KIDS_GAMES: KidsGame[] = [
  {
    slug: 'hue-perfect',
    name: 'Hue Perfect',
    emoji: '🎨',
    description: 'See a colour for a few seconds — then recreate it from memory using HSB sliders.',
    rules: [
      'A colour swatch is shown on screen. Memorise it — you only have a few seconds!',
      'The colour disappears. Use the Hue, Saturation, and Brightness sliders to mix it back.',
      'Submit your guess. The closer your match, the higher your score (out of 100 per round).',
      'In multiplayer, each player takes their own turn each round. Highest total score wins!',
    ],
    examples: [],
    prompts: [],
    reminder: 'Memorise the colour, then mix it from memory!',
    mistakeLabel: '',
  },
  {
    slug: 'say-the-color',
    name: 'Say the Color',
    emoji: '🌈',
    description: 'Say the FONT COLOR of each word — not the word itself. Can your brain handle the Stroop effect?',
    rules: [
      'Look at each word on screen — but say its FONT COLOR out loud, not what the word says.',
      'Example: "RED" written in blue → say "Blue".',
      'Everyone attempts the same sequence each round. The host marks who got it right.',
      'The sequence gets longer every time at least one player succeeds. +1 point for a correct run!',
    ],
    examples: [
      { question: 'GREEN written in red font', answer: 'Say "Red"!' },
      { question: 'BLUE written in yellow font', answer: 'Say "Yellow"!' },
    ],
    prompts: [],
    reminder: 'Say the color you SEE, not the word you READ!',
    mistakeLabel: '',
  },
  {
    slug: 'dont-say-yes-or-no',
    name: "Don't Say Yes or No",
    emoji: '🤐',
    description: 'Think fast! Answer every question without saying "yes" or "no".',
    rules: [
      'Ask each other questions, but never say "yes" or "no". Answer with a sentence instead.',
      "Keep the questions coming rapid-fire and answer immediately — don't pause to think!",
      `Say "yes" or "no" by mistake and you're out.`,
      'Take turns answering. The last player still in wins!',
    ],
    examples: [
      { question: 'Do you like pizza?', answer: 'I love it!' },
      { question: 'Did you go to school today?', answer: 'I went this morning.' },
      { question: 'Can you swim?', answer: 'Of course I can!' },
    ],
    prompts: [
      'Do you like pizza?',
      'Did you go to school today?',
      'Can you swim?',
      'Is your favourite colour blue?',
      'Do you have a pet?',
      'Are you wearing shoes right now?',
      'Would you like some ice cream?',
      'Can you ride a bike?',
      'Do you like rainy days?',
      'Have you ever seen a rainbow?',
      'Are you good at dancing?',
      'Do you like broccoli?',
      'Can you count to ten?',
      'Is your birthday in summer?',
      'Do you like drawing?',
      'Have you ever been on a train?',
      'Would you like to visit the moon?',
      'Can you touch your toes?',
      'Do you like bedtime stories?',
      'Have you ever built a sandcastle?',
      'Would you hug a dinosaur?',
      'Can you make a funny face?',
      'Do you like to sing?',
      'Do you like chocolate?',
      'Have you ever eaten sushi?',
      'Can you whistle?',
      'Do you have a favourite movie?',
      'Are you taller than your best friend?',
      'Have you ever been to a concert?',
      'Can you juggle?',
      'Would you swim with sharks?',
      'Have you ever stayed up past midnight?',
      'Do you like spicy food?',
      'Can you do a cartwheel?',
      'Are you afraid of spiders?',
      'Have you ever broken a bone?',
      'Do you prefer summer over winter?',
      'Can you snap your fingers?',
      'Have you ever been on a plane?',
      'Do you like waking up early?',
      'Have you ever won a competition?',
      'Can you tie your shoelaces with your eyes closed?',
      'Do you like roller coasters?',
      'Have you ever seen snow?',
      'Are you good at keeping secrets?',
      'Do you like doing homework?',
      'Can you do a handstand?',
      'Have you ever cooked a meal?',
      'Do you like camping?',
      'Would you eat a bug for a hundred pounds?',
      'Can you name three capital cities?',
      'Have you ever dyed your hair?',
      'Are you scared of the dark?',
      'Have you ever fallen asleep somewhere funny?',
      'Do you like shopping?',
      'Have you ever met someone famous?',
      'Do you like thunderstorms?',
      'Would you live on a desert island?',
      'Can you hold your breath for thirty seconds?',
      'Do you like spiders?',
      'Are you a good cook?',
      'Have you ever been to a museum?',
      'Do you prefer coffee over tea?',
      'Have you ever seen a shooting star?',
      'Do you like reading books?',
      'Can you do the splits?',
      'Have you ever lost something important?',
      'Do you like board games?',
      'Have you ever been to a farm?',
      'Do you prefer pizza over burgers?',
      'Are you good at maths?',
      'Have you ever slept in a tent?',
      'Do you like video games?',
      'Have you ever been on TV?',
      'Do you like surprises?',
      'Are you a morning person?',
      "Have you ever forgotten someone's birthday?",
      'Do you like horror movies?',
      'Can you do a magic trick?',
      'Have you ever been on a boat?',
      'Do you like fizzy drinks?',
      'Are you good at spelling?',
      'Have you ever grown a plant from a seed?',
      'Would you skydive if given the chance?',
      'Have you ever been in a school play?',
      'Do you prefer sweet or savoury snacks?',
      'Can you name every planet in the solar system?',
      'Have you ever ridden a horse?',
      'Do you like going to the cinema?',
      'Are you good at drawing people?',
      'Have you ever been abroad?',
      'Do you like the smell of rain?',
      'Can you remember your dreams?',
      'Have you ever helped a stranger?',
      'Do you like trying new foods?',
      'Are you scared of flying?',
      'Have you ever stayed in a hotel?',
      'Do you like watching sport?',
      "Can you name a song that's in the charts right now?",
      'Have you ever made someone cry laughing?',
      'Do you prefer showers over baths?',
      'Are you good at remembering names?',
      'Have you ever been to a wedding?',
    ],
    reminder: `Answer with a sentence. Don't say "yes" or "no"!`,
    mistakeLabel: 'Said yes or no — out!',
  },
  {
    slug: 'wrong-answers-only',
    name: 'Wrong Answers Only',
    emoji: '🙃',
    description: 'Simple questions. Silly answers. Being wrong is how you win!',
    rules: [
      'Ask each other simple questions — every answer has to be wrong!',
      'Answer quickly before your brain gives away the right answer.',
      'Keep the questions coming quickly. The sillier the answers, the better!',
      "Give the correct answer by mistake and you're out. The last player still in wins!",
    ],
    examples: [
      { question: 'What colour is the sky?', answer: 'Pink!' },
      { question: 'How many legs does a dog have?', answer: 'Seven!' },
      { question: 'Where do fish live?', answer: 'In a cupboard!' },
    ],
    prompts: [
      'What colour is the sky on a clear day?',
      'How many legs does a dog have?',
      'Where do fish live?',
      'What sound does a cow make?',
      'What do you brush your teeth with?',
      'What do you wear on your feet?',
      'What do bees make?',
      'What do you sleep on?',
      'How many wheels does a bicycle have?',
      'What do you use to see?',
      'What animal says "meow"?',
      'What do you use to write on paper?',
      'What do you open when it rains to stay dry?',
      'Where do you put a hat?',
      'What is two plus two?',
      'What colour is grass?',
      'What do chickens lay?',
      'What do you drink when you are thirsty?',
      'What do you use to hear?',
      'What fruit do monkeys love to eat?',
      'What do you kick in football?',
      'What shines in the sky during the day?',
      'What do you wear to keep your hands warm?',
      'What do you use to cut paper?',
      'What do you call a baby dog?',
      'What colour is a tomato?',
      'How many days are in a week?',
      'What do you call the season with snow?',
      'What do you wash your body with?',
      'What do you use to sweep the floor?',
      'What do you look at to tell the time?',
      'What sound do frogs make?',
      'How many letters are in the alphabet?',
      'What do you breathe in to stay alive?',
      'What do birds have instead of arms?',
      'What colour is a banana?',
      'What do cats say?',
      'How many sides does a triangle have?',
      'What colour is coal?',
      'What do you put in a toaster?',
      'How many fingers do you have on one hand?',
      'What is ice when it melts?',
      'What do dogs bury in the garden?',
      'What do you use to stir soup?',
      'What comes after Monday?',
      'What do butterflies come from?',
      'What colour is a stop sign?',
      'How many hours are in a day?',
      'What do you put stamps on?',
      'How many wheels does a car have?',
      'What colour are polar bears?',
      'What do you use to row a boat?',
      'How many legs does a spider have?',
      'What do squirrels collect in autumn?',
      'What do you wear on your head to ride a bike safely?',
      'What is the biggest planet in our solar system?',
      'What do you use to unlock a door?',
      'How many sides does a square have?',
      'What do you call the room where you sleep?',
      'What do cows eat?',
      'What colour is the sun?',
      'How many zeros are in one thousand?',
      'What do you call a baby cat?',
      'What is the opposite of hot?',
      'How many seconds are in one minute?',
      'What colour is a flamingo?',
      'How many sides does a hexagon have?',
      'What is two times five?',
      'What do you call a person who fixes teeth?',
      'What is the capital of France?',
      'How many eyes do humans have?',
      'What animal has a very long neck?',
      'What colour is an orange?',
      'What do you wear when you go swimming?',
      'What is the smallest number you can count?',
      'What do you use to take a photo?',
      'What colour is a ripe strawberry?',
      'How many months are in a year?',
      'What do you call a baby frog?',
      'What do you use to eat soup?',
      'What is the shape of a football?',
      'What do you call the person who delivers your letters?',
      'How many legs does a bird have?',
      'What do you use to make a phone call?',
      'What colour is chocolate?',
      'How many sides does a pentagon have?',
      'What do you call frozen water falling from the sky?',
      'What is the fastest land animal?',
      'How many zeros are in one hundred?',
      'What do you call a house made of snow and ice?',
      'What colour is a school bus?',
      'How many planets are in our solar system?',
      'What do you call the thing bees live in?',
      'What colour is milk?',
      'How many ears do humans have?',
      'What do you call a very big hairy spider?',
      'What colour is a ladybird?',
      'How many wheels does a tricycle have?',
      'What do you call a group of fish?',
      'What is the largest ocean?',
      'What do you wear over your pyjamas when it is cold?',
      'What colour is a ripe lemon?',
    ],
    reminder: 'Answer quickly. Make it wrong — and make it silly!',
    mistakeLabel: 'Correct answer — out!',
  },
]

export function getKidsGame(slug: string) {
  return KIDS_GAMES.find(game => game.slug === slug)
}
